### PR TITLE
Fixing squid: S1213 The members of an interface declaration or class should appear in a pre-defined order

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1213 - “The members of an interface declaration or class should appear in a pre-defined order”. This PR will remove 4h TD from the project.
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1213
 Please let me know if you have any questions.
 Fevzi Ozgul

### CODE REVIEW

**Comment by ernstsson** [comment]
Doesn't really seem to follow the style of the library, we intentionally put empty private constructors in the end of each file since we find it to be the least important information in there (especially for utility classes)

**Comment by JoseAlcerreca** [comment]
-1

**Comment by devFozgul** [comment]
OK, if you have intentionally done so. I will change those lines to the original and change only the locations  of the instance and class variables' then. Is that OK for you?

**Comment by ernstsson** [comment]
I actually don't see the point. The code is structured in a logical way that makes sense to the context it's in.

**Pull request closed without merging**
