### PR TITLE
Added support for more sql content values

### LINKED ISSUE #97: About supporting more content values in DBColumn
https://github.com/google/agera/blob/master/extensions/database/src/main/java/com/google/android/agera/database/SqlRequestCompiler.java#L93

The `SqlRequestCompiler#column` method only support `String` value, what about other content values such as `byte[]` for saving BLOB to SQLite? What should I do? DB module seems to be limited. Maybe we could add more `column` methods in `DBColumn`?

### PR DESCRIPTION
**Pull request by ernstsson**
Fixes #97

### CODE REVIEW

**Comment by ernstsson** [comment]
@drakeet like this?

**Comment by drakeet** [comment]
Great! This is exactly what I want, lol

**Comment by ernstsson** [comment]
Cool. If you need a binary drop of this I could make a 1.2.0-beta1 early next week.

**Comment by drakeet** [comment]
Thank you, I'm looking forward to it but not urgent.

**Pull request merged**
