### PR TITLE
Change the default charset of HTTP responses to UTF-8.

### PR DESCRIPTION
**Pull request by swankjesse**
It's the right thing to do.
https://googleblog.blogspot.ch/2012/02/unicode-over-60-percent-of-web.html

### CODE REVIEW

**Comment by ernstsson** [comment]
Thanks for the PR. firstly for contributions, please check CONTRIBUTING.md. Secondly, correct me if I'm wrong but I was sure [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html) says that "When no explicit charset parameter is provided by the sender, media subtypes of the "text" type are defined to have a default charset value of "ISO-8859-1" when received via HTTP. Data in character sets other than "ISO-8859-1" or its subsets MUST be labeled with an appropriate charset value.". I would assume that not setting the charset means ISO-8859-1 and that UTF-8 being used by 60% of the web as of 2012 only means that "charset=utf-8" is now sent more often by servers? Standard and tradition sometimes can a tendency to diverge over time though.

**Comment by swankjesse** [comment]
The recommendation of ISO-8859-1 as a default was removed when the HTTP spec was revised.
https://tools.ietf.org/html/rfc7231#appendix-B

See this site for a good explanation of why UTF-8 is a better default.
http://utf8everywhere.org/

**Comment by ernstsson** [comment]
Awesome, turns out tradition sometimes change standard too. Thanks!

**Comment by swankjesse** [comment]
PR closed but not merged?

**Comment by swankjesse** [comment]
Ah, found it. Thanks!

**Comment by ernstsson** [comment]
Yeah, had to rebase and also change the test case for it, but it's there (not sure, github sometimes can't associate a locally rebased commit with a PR, but maybe it's because I edited it).

**Pull request closed without merging**
